import { Geist, Geist_Mono } from "next/font/google";
import { UserProvider } from '@auth0/nextjs-auth0/client';
import "./globals.css";

// FORCE DEPLOYMENT VERIFICATION - Ensure Vercel builds our professional features
const DEPLOYMENT_MARKER = "PROFESSIONAL_FLOWLYNC_v2.0_" + new Date().getTime();
console.log("🚀 FlowLync Professional Deployment:", DEPLOYMENT_MARKER);

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
